# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: cyber4paleo Community Development
email: goring@wisc.edu
description: > # this means to ignore newlines until "baseurl:"
  A website for the EarthCube Cyber4Paleo Community Development
  Workshop - June 2016, Boulder CO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cyber4paleo.github.io" # the base hostname & protocol for your site
github_username:  cyber4paleo

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
  resources:
    output: true
